name: global-q-explorer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit>=1.28.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - plotly>=5.18.0
  - seaborn>=0.13.0
  - scipy>=1.11.0
  - pip
  - pip:
    - yfinance>=0.2.31 